//! Persisted GUI settings: media root(s) and TMDb API key. Kept separate
//! from `ServerCore`'s own state (STUN link, library) because these are
//! needed *before* a core can even be constructed. The packaged desktop app
//! deliberately has no environment-only media-root configuration path.

use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use std::process::Command;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct MediaRootSetting {
    pub label: String,
    pub path: String,
    /// A safe OS mount URL captured while a network share is healthy. This
    /// lets the background health monitor ask macOS to remount the share
    /// after SMB drops without storing a password in settings.json.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reconnect_url: Option<String>,
}

/// A lightweight accessibility check used by the desktop UI. Opening the
/// directory (rather than merely checking `Path::exists`) also catches a
/// mounted network share that is present but no longer readable.
#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct MediaRootHealth {
    pub label: String,
    pub path: String,
    pub available: bool,
    pub error: Option<String>,
    pub auto_reconnect: bool,
}

pub fn media_root_health(roots: &[MediaRootSetting]) -> Vec<MediaRootHealth> {
    roots
        .iter()
        .map(|root| match std::fs::read_dir(&root.path) {
            Ok(_) => MediaRootHealth {
                label: root.label.clone(),
                path: root.path.clone(),
                available: true,
                error: None,
                auto_reconnect: root.reconnect_url.is_some(),
            },
            Err(error) => MediaRootHealth {
                label: root.label.clone(),
                path: root.path.clone(),
                available: false,
                error: Some(error.to_string()),
                auto_reconnect: root.reconnect_url.is_some(),
            },
        })
        .collect()
}

/// Fill in reconnect URLs for currently mounted macOS SMB shares. Returns
/// true when settings changed and should be persisted.
pub fn populate_reconnect_urls(settings: &mut Settings) -> bool {
    let mut changed = false;
    for root in &mut settings.media_roots {
        if root.reconnect_url.is_none() {
            if let Some(url) = discover_reconnect_url(&root.path) {
                root.reconnect_url = Some(url);
                changed = true;
            }
        }
    }
    changed
}

pub fn discover_reconnect_url(path: &str) -> Option<String> {
    #[cfg(target_os = "macos")]
    {
        let output = Command::new("/sbin/mount").output().ok()?;
        let text = String::from_utf8_lossy(&output.stdout);
        return reconnect_url_from_mount_output(path, &text);
    }
    #[cfg(not(target_os = "macos"))]
    {
        let _ = path;
        None
    }
}

/// Best-effort remount. The URL is generated by this module and contains no
/// password; macOS resolves saved credentials from Keychain/mount state.
pub fn reconnect_network_root(root: &MediaRootSetting) -> std::io::Result<bool> {
    let Some(url) = root
        .reconnect_url
        .as_deref()
        .filter(|url| url.starts_with("smb://") || url.starts_with("afp://"))
    else {
        return Ok(false);
    };
    #[cfg(target_os = "macos")]
    {
        return Command::new("/usr/bin/open")
            .args(["-g", url])
            .status()
            .map(|status| status.success());
    }
    #[cfg(not(target_os = "macos"))]
    {
        let _ = url;
        Ok(false)
    }
}

fn reconnect_url_from_mount_output(path: &str, output: &str) -> Option<String> {
    output
        .lines()
        .filter_map(|line| {
            let (source, remainder) = line.split_once(" on ")?;
            let (mount_point, _) = remainder.rsplit_once(" (")?;
            let mount_point = mount_point.replace("\\040", " ");
            let root_matches = path == mount_point
                || path
                    .strip_prefix(&mount_point)
                    .is_some_and(|rest| rest.starts_with('/'));
            if !root_matches {
                return None;
            }
            let scheme = if source.starts_with("//") {
                "smb"
            } else {
                return None;
            };
            let authority_and_path = source.trim_start_matches('/');
            let sanitized = if let Some((userinfo, host_path)) = authority_and_path.split_once('@')
            {
                let user = userinfo.split(':').next().unwrap_or_default();
                if user.is_empty() {
                    host_path.to_string()
                } else {
                    format!("{user}@{host_path}")
                }
            } else {
                authority_and_path.to_string()
            };
            Some((mount_point.len(), format!("{scheme}://{sanitized}")))
        })
        .max_by_key(|(mount_len, _)| *mount_len)
        .map(|(_, url)| url)
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Settings {
    #[serde(default)]
    pub media_roots: Vec<MediaRootSetting>,
    /// Superseded by `media_roots` — read-only now, kept only so an older
    /// settings.json (single-root, pre-this-field) still loads. Never
    /// written by this build; see `load`'s one-time upgrade below.
    #[serde(default)]
    media_root: Option<String>,
    pub tmdb_api_key: Option<String>,
    /// OpenSubtitles.com REST API key used only for user-requested subtitle
    /// search/downloads. The settings file is permission-restricted (0600).
    #[serde(default)]
    pub opensubtitles_api_key: Option<String>,
    /// Applies the measured upload budget to internet playback. LAN
    /// playback always bypasses it regardless of this setting.
    #[serde(default = "default_streaming_upload_budget_enabled")]
    pub streaming_upload_budget_enabled: bool,
    /// Generate English subtitles locally with Whisper. The model and queue
    /// live in app data; disabling pauses work without discarding progress.
    #[serde(default)]
    pub local_transcription_enabled: bool,
    /// Protect playback from Whisper's sustained CPU load. Users with CPU
    /// headroom can opt out and allow both workloads to run concurrently.
    #[serde(default = "default_transcription_pause_while_streaming")]
    pub transcription_pause_while_streaming: bool,
    /// Whether the read-only MCP server (see `mcp.rs`) starts alongside the
    /// GUI app's core. Takes effect on next launch/restart — no hot-reload,
    /// same posture as `media_root`'s pre-multi-root upgrade above having no
    /// live-apply path either.
    #[serde(default)]
    pub mcp_enabled: bool,
    #[serde(default = "default_mcp_port")]
    pub mcp_port: u16,
    /// Bearer token required by every MCP request.
    #[serde(default)]
    pub mcp_access_token: Option<String>,
}

fn default_streaming_upload_budget_enabled() -> bool {
    true
}

fn default_transcription_pause_while_streaming() -> bool {
    true
}

fn default_mcp_port() -> u16 {
    7890
}

// Hand-written rather than `#[derive(Default)]` so a brand-new install (no
// settings.json at all, going through `Settings::default()` in `load` below)
// gets the exact same `mcp_port` default as an *existing* settings.json
// that simply predates this field (going through serde's per-field
// `#[serde(default = "default_mcp_port")]`) — a derived `Default` would
// silently disagree (`u16::default()` is `0`, not `default_mcp_port()`).
impl Default for Settings {
    fn default() -> Self {
        Settings {
            media_roots: Vec::new(),
            media_root: None,
            tmdb_api_key: None,
            opensubtitles_api_key: None,
            streaming_upload_budget_enabled: true,
            local_transcription_enabled: false,
            transcription_pause_while_streaming: true,
            mcp_enabled: false,
            mcp_port: default_mcp_port(),
            mcp_access_token: None,
        }
    }
}

fn settings_path(app_data_dir: &Path) -> PathBuf {
    app_data_dir.join("settings.json")
}

/// Loads persisted settings, transparently upgrading a pre-multi-root
/// settings.json (single `media_root: Option<String>`, no `media_roots`)
/// into the new shape in memory. Not written back to disk here — the next
/// `save` call (any settings change) persists the upgraded shape naturally.
pub fn load(app_data_dir: &Path) -> Settings {
    let mut settings: Settings = std::fs::read_to_string(settings_path(app_data_dir))
        .ok()
        .and_then(|contents| serde_json::from_str(&contents).ok())
        .unwrap_or_default();
    if settings.media_roots.is_empty() {
        if let Some(path) = settings.media_root.take() {
            settings.media_roots.push(MediaRootSetting {
                label: "local".to_string(),
                path,
                reconnect_url: None,
            });
        }
    }
    settings
}

pub fn save(app_data_dir: &Path, settings: &Settings) -> std::io::Result<()> {
    std::fs::create_dir_all(app_data_dir)?;
    let json = serde_json::to_string_pretty(settings).unwrap_or_default();
    let path = settings_path(app_data_dir);
    std::fs::write(&path, json)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))?;
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn older_settings_keep_the_upload_budget_enabled() {
        let dir =
            std::env::temp_dir().join(format!("swarm-settings-test-{}", rand::random::<u64>()));
        std::fs::create_dir_all(&dir).unwrap();
        std::fs::write(
            settings_path(&dir),
            r#"{"media_roots":[{"label":"local","path":"/media"}],"tmdb_api_key":null,"mcp_enabled":false,"mcp_port":7890}"#,
        )
        .unwrap();
        let loaded = load(&dir);
        assert!(loaded.streaming_upload_budget_enabled);
        assert!(!loaded.local_transcription_enabled);
        assert!(loaded.transcription_pause_while_streaming);
        assert_eq!(loaded.mcp_access_token, None);
        std::fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn media_root_health_reports_readable_and_missing_roots() {
        let dir =
            std::env::temp_dir().join(format!("swarm-root-health-test-{}", rand::random::<u64>()));
        std::fs::create_dir_all(&dir).unwrap();
        let missing = dir.join("disconnected-share");
        let roots = vec![
            MediaRootSetting {
                label: "local".into(),
                path: dir.to_string_lossy().into_owned(),
                reconnect_url: None,
            },
            MediaRootSetting {
                label: "nas".into(),
                path: missing.to_string_lossy().into_owned(),
                reconnect_url: Some("smb://nas/share".into()),
            },
        ];

        let health = media_root_health(&roots);
        assert!(health[0].available);
        assert_eq!(health[0].error, None);
        assert!(!health[1].available);
        assert!(health[1].error.is_some());
        assert!(health[1].auto_reconnect);

        std::fs::remove_dir_all(dir).unwrap();
    }

    #[test]
    fn macos_mount_output_selects_longest_share_and_strips_password() {
        let mounts = "//guest:secret@nas.local/share on /Volumes/share (smbfs, nodev)\n//other@nas.local/archive on /Volumes/archive (smbfs)";
        assert_eq!(
            reconnect_url_from_mount_output("/Volumes/share/movies", mounts).as_deref(),
            Some("smb://guest@nas.local/share")
        );
    }
}
